### ISSUE TITLE
`ThermalItemGroups` annotate `CreativeModeTab.makeIcon()` as `OnlyIn(Dist.CLIENT)` despite the super method not being annotated as such. 

### ISSUE THREAD

**Issue by alcatrazEscapee** [CoFH/ThermalCore#9]
This bit of code:

https://github.com/CoFH/ThermalCore/blob/bf9ab1855be8a03e6498421156d288d53ce3b075/src/main/java/cofh/thermal/lib/common/ThermalItemGroups.java#L37-L39

Thermal is annotating a vanilla method as `@OnlyIn(Dist.CLIENT)`, which causes it to be not present in dedicated server, despite **the vanilla method not being annotated as such**. In particular, vanilla stopped side-specific method stripping like this since 1.17.

This has the effect of stripping out the method implementation in a dedicated server, meaning any other mod which calls `makeIcon()` has the potential to cause a crash.

I ran into this issue in 1.18.2, with another mod which was calling `makeIcon()` on dedicated server in a loop over all creative tabs - which then crashes with an `AbstractMethodError`

Mods / Versions:

- TerraFirmaCraft 2.2.8
- Forge 40.1.2
- Minecraft 1.18.2

Example crash log, invoking the `AbstractMethodError` which can occur:

[crash-2023-02-15_19.09.47-fml.txt](https://github.com/CoFH/ThermalCore/files/10750758/crash-2023-02-15_19.09.47-fml.txt)

---

Side note: I wasn't sure what repo to report this to - I discovered the issue on 1.18.2, and I believe I've tracked the offending code to `ThermalItemGroups` but the branch name is `1.19.x` and I wasn't able to see anywhere else where it was declared. Forgive me if this is the wrong location.

**Comment by KingLemming** [comment]
Mmm. Yeah the issue here is that the issue tracker is still open on this repo. You're meant to report stuff like this on our Discord.

Fixed in dev, will be handled...at some point, frankly.
